import Button from '@material-ui/core/Button'
import { makeStyles } from '@material-ui/core/styles'

//import NferxCard from 'nferx-core-ui/src/widgets/NferxCard'
// import NferxCard from 'nferx-core-ui/src/widgets/Typography'

import {
  NferxCard,
  Typography
} from 'nferx-core-ui'

const useStyles = makeStyles(theme => ({
  card: {},
  heading: {
    marginBottom: [ theme.pad.sm, '!important' ],
    marginTop: [theme.pad.sm, '!important' ]
  },
  outerContainer: {
    padding: theme.pad.sm,
    width: '100%',
  },
  innerContainer: {
    maxWidth: 500,
    width: '100%',
    margin: [ 0, 'auto', 0, 'auto' ],
  },
  mfaSubSection: {position: 'inline'},
  button: {
    minWidth: '40%',
    margin: 10,
    marginLeft: 0
  }
}))

function MfaHelpRouteContents(props) {

    const classes = useStyles();
    return (
      <div className={classes.outerContainer}>
        <div className={classes.innerContainer}>
            <NferxCard
              headerVariant={'detached'}
              contentPad variant={'flat'}
            >
                <div className={classes.mfaSubSection}>
                    <Typography variant={'h1'} style={{ marginBottom: 16 }}> 1. Update "Date & time" settings on your phone</Typography>
                    <div className={'download-auth-app'}>
                        <Typography style={{ marginBottom: 16 }}>
                            <div>
If a cell phone's clock / calendar is off by a significant amount of time, it would be unable to authenticate correctly with the OTP generated by the TOTP (Time-based OTP) algorithm. The OTP is not exactly an invalid, just a token for a different time. So make sure to enable these settings on your smartphone
                            </div><br />
                            <div>
                                1. Go to "Settings". <br/>
                                2. Choose "Date & time". <br/>
                                3. Enable "Use network-provided time" and "Use network-provided time zone" <br/>
                            </div>
                        </Typography>
                    </div>
                </div>
                <div className={classes.mfaSubSection}>
                    <Typography variant={'h1'} style={{ marginBottom: 16 }}> 2. Time correction for codes (For Google Authenticator app)</Typography>
                    <div className={'download-auth-app'}>
                        <Typography style={{ marginBottom: 16 }}>
                            <div>
                                The codes that Google Authenticator generates depend on the correct time on your Android device. If your verification codes generated by Google Authenticator aren’t working, it might be because the time on your Android device is incorrect. To fix this, you can use the Time sync feature on the Authenticator app. Time sync will confirm whether an incorrect time is the root cause of the issue, and, if so, will sync your time to that of Google’s servers.
                            </div><br />
                            <div>
                                If you see <b>"Invalid verification code"</b> error while entering the verification code,
                                sync the time on your Google Authenticator app by following these steps: <br/>

                                1. Open the Google Authenticator app. <br/>
                                2. Tap More  and then Settings. <br/>
                                3. Tap Time correction for codes. <br/>
                                4. Tap Sync now. <br/>
                            </div>
                        </Typography>
                    </div>
                </div>
                <div className={classes.mfaSubSection}>
                    <Typography variant={'h1'} style={{ marginBottom: 16 }}> 3. Get recovery codes</Typography>
                    <Typography style={{ marginBottom: 16 }}>
                        Click on the below link to generate the recovery codes
                            <Button
                                variant='outlined'
                                color='primary'
                                className={classes.button}
                                component={'a'}
                                href='/auth/generate-recovery-codes/'
                                target='_blank'
                            >
                                Generate codes
                            </Button>
                    </Typography>
                </div>
                <div className={classes.mfaSubSection}>
                    <Typography variant={'h1'} style={{ marginBottom: 16 }}> 4. If the app is deleted in Authenticator app OR incase of the mobile phone is lost </Typography>
                    <Typography style={{ marginBottom: 16 }}>
                        1. Get the recovery codes. See the above section <br />
                        2. Sign in to the nferX account <br/>
                        3. It will take to Verify Two-Factor Authentication page <br/>
                        4. Enter one of the recovery codes <br/>
                        5. Now disable MFA using <a href='/auth/disable-mfa/' target='_blank'>disable-mfa</a> link <br/>
                        6. You will take to Configure MFA page <br/>
                        7. Download the authenticator app on the phone and scan the QR code to enable the MFA. <br/>
                    </Typography>
                </div>
            </NferxCard>
        </div>
      </div>
    )
}

export default MfaHelpRouteContents
